version: '3.8'

services:

  postgres-14:
    image: postgres:14.5
    expose:
      - 5432
    env_file:
      - ./.env
    volumes:
      - ./init-user-db.sql:/docker-entrypoint-initdb.d/init-user-db.sql

  web-server:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8080
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - postgres-14
